AWSTemplateFormatVersion: "2010-09-09"
Resources:

  ##### ec2 start #####

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0e8a20c6da2c1ffbe"
      InstanceType: "t2.micro"
      KeyName: "skillsontario"
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      SubnetId: !Ref  PublicSubnet1

  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH access to EC2 instance"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"

  ##### ec2 end #####

  ##### rds start #####
  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "skillsdb"
      DBSnapshotIdentifier: "arn:aws:rds:us-east-1:156463586173:snapshot:skillsdb-snapshot"
      DBInstanceClass: "db.t2.micro"
      Engine: "mysql"
      AllocatedStorage: "5"
      DBSubnetGroupName: !Ref RDSSubnetGroup
      MultiAZ: False
      PubliclyAccessible: False

  RDSSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: "skillsdb-subnet-group"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  ##### rds end #####

  ##### alb start #####
  ALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "skillsdb-alb"
      Subnets: !Ref PublicSubnets
      SecurityGroups: !Ref ALBSecurityGroup

  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTP access to ELB"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"

  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: "80"
      Protocol: "HTTP"
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref ALBTargetGroup

  ALBTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      VpcId: !Ref VPC
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: "/"
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: "deregistration_delay.timeout_seconds"
          Value: "60"

  ##### alb end #####


Outputs:
  ALBDNSName:
    Description: The DNS name of the ALB
    Value: !GetAtt ALB.DNSName

  EC2InstanceIP:
    Description: The IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
