AWSTemplateFormatVersion: 2010-09-09
Resources:

  # VPC

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  # Subnets

  PrivateSubnets:
    Type: AWS::EC2::Subnet::Collection
    Properties:
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Private Subnets

  PublicSubnets:
    Type: AWS::EC2::Subnet::Collection
    Properties:
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Public Subnets

  # Internet Gateway

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Internet Gateway

  # Route Tables

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Private Route Table

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Public Route Table

  # Routes

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: !GetAtt VPC.CidrBlock
      DependsOn: PrivateRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      DependsOn: PublicRouteTable

  # Route Tables Association

  PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  # NAT Gateway

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet1
      AllocationId: !GetAtt EIP.AllocationId

  # Outputs

  Outputs:
    VpcId:
      Description: "The VPC ID"
      Value: !Ref VPC

    PublicSubnet1:
      Description: "The public subnet 1 ID"
      Value: !Ref PublicSubnet1

    PublicSubnet2:
      Description: "The public subnet 2 ID"
      Value: !Ref PublicSubnet2

    PrivateSubnet1:
      Description: "The private subnet 1 ID"
      Value: !Ref PrivateSubnet1

    PrivateSubnet2:
      Description: "The private subnet 2 ID"
      Value: !Ref PrivateSubnet2

    InternetGateway:
      Description: "The internet gateway ID"
      Value: !Ref InternetGateway